apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: development-ingress
  namespace: development
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: api.richard.io
      http:
        paths:
          - backend:
              service:
                name: express-service
                port:
                  number: 80
            path: /*
            pathType: ImplementationSpecific
