apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${IMAGENAME}
  name: ${IMAGENAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${IMAGENAME}
  template:
    metadata:
      labels:
        app: ${IMAGENAME}
    spec:
      containers:
        - image: ${DOCKERHUB}/${IMAGENAME}:${VERSION}
          name: ${IMAGENAME}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database
                  key: MYSQL_PASSWORD
